In [1]:
import pandas as pd
import numpy as np
import seaborn as sans
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("dow_jones_index.csv")
data

quarter stock       date    open    high     low   close     volume  \
0          1    AA   1/7/2011  $15.82  $16.72  $15.78  $16.42  239655616   
1          1    AA  1/14/2011  $16.71  $16.71  $15.64  $15.97  242963398   
2          1    AA  1/21/2011  $16.19  $16.38  $15.60  $15.79  138428495   
3          1    AA  1/28/2011  $15.87  $16.63  $15.82  $16.13  151379173   
4          1    AA   2/4/2011  $16.18  $17.39  $16.18  $17.14  154387761   
..       ...   ...        ...     ...     ...     ...     ...        ...   
745        2   XOM  5/27/2011  $80.22  $82.63  $80.07  $82.63   68230855   
746        2   XOM   6/3/2011  $83.28  $83.75  $80.18  $81.18   78616295   
747        2   XOM  6/10/2011  $80.93  $81.87  $79.72  $79.78   92380844   
748        2   XOM  6/17/2011  $80.00  $80.82  $78.33  $79.02  100521400   
749        2   XOM  6/24/2011  $78.65  $81.12  $76.78  $76.78  118679791   

     percent_change_price  percent_change_volume_over_last_wk  \
0                 3.79267                                 NaN   
1                -4.42849                            1.380223   
2                -2.47066                          -43.024959   
3                 1.63831                            9.355500   
4                 5.93325                            1.987452   
..                    ...                                 ...   
745               3.00424                          -21.355713   
746              -2.52161                           15.221032   
747              -1.42098                           17.508519   
748              -1.22500                            8.811952   
749              -2.37762                           18.064204   

     previous_weeks_volume next_weeks_open next_weeks_close  \
0                      NaN          $16.71           $15.97   
1              239655616.0          $16.19           $15.79   
2              242963398.0          $15.87           $16.13   
3              138428495.0          $16.18           $17.14   
4              151379173.0          $17.33           $17.37   
..                     ...             ...              ...   
745             86758820.0          $83.28           $81.18   
746             68230855.0          $80.93           $79.78   
747             78616295.0          $80.00           $79.02   
748             92380844.0          $78.65           $76.78   
749            100521400.0          $76.88           $82.01   

     percent_change_next_weeks_price  days_to_next_dividend  \
0                          -4.428490                     26   
1                          -2.470660                     19   
2                           1.638310                     12   
3                           5.933250                      5   
4                           0.230814                     97   
..                               ...                    ...   
745                        -2.521610                     75   
746                        -1.420980                     68   
747                        -1.225000                     61   
748                        -2.377620                     54   
749                         6.672740                     47   

     percent_return_next_dividend  
0                        0.182704  
1                        0.187852  
2                        0.189994  
3                        0.185989  
4                        0.175029  
..                            ...  
745                      0.568801  
746                      0.578960  
747                      0.589120  
748                      0.594786  
749                      0.612139  

[750 rows x 16 columns]

In [3]:
data['high'] = data['high'].str.replace('$', '')
data['open'] = data['open'].str.replace('$', '')
data['low'] = data['low'].str.replace('$', '')
data['close'] = data['close'].str.replace('$', '')
data['next_weeks_open'] = data['next_weeks_open'].str.replace('$', '')
data['next_weeks_close'] = data['next_weeks_close'].str.replace('$', '')

C:\Users\HP\AppData\Local\Temp\ipykernel_7144\598260326.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['high'] = data['high'].str.replace('$', '')
C:\Users\HP\AppData\Local\Temp\ipykernel_7144\598260326.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['open'] = data['open'].str.replace('$', '')
C:\Users\HP\AppData\Local\Temp\ipykernel_7144\598260326.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['low'] = data['low'].str.replace('$', '')
C:\Users\HP\AppData\Local\Temp\ipykernel_7144\598260326.p

In [4]:
data['high']=pd.to_numeric(data['high'])
data['open']=pd.to_numeric(data['open'])
data['low']=pd.to_numeric(data['low'])
data['close']=pd.to_numeric(data['close'])
data['next_weeks_open']=pd.to_numeric(data['next_weeks_open'])
data['next_weeks_close']=pd.to_numeric(data['next_weeks_close']) 

In [5]:
data['percent_change_volume_over_last_wk'].fillna(value=0,inplace=True)
data['previous_weeks_volume'].fillna(value=0,inplace=True)

In [6]:
data

quarter stock       date   open   high    low  close     volume  \
0          1    AA   1/7/2011  15.82  16.72  15.78  16.42  239655616   
1          1    AA  1/14/2011  16.71  16.71  15.64  15.97  242963398   
2          1    AA  1/21/2011  16.19  16.38  15.60  15.79  138428495   
3          1    AA  1/28/2011  15.87  16.63  15.82  16.13  151379173   
4          1    AA   2/4/2011  16.18  17.39  16.18  17.14  154387761   
..       ...   ...        ...    ...    ...    ...    ...        ...   
745        2   XOM  5/27/2011  80.22  82.63  80.07  82.63   68230855   
746        2   XOM   6/3/2011  83.28  83.75  80.18  81.18   78616295   
747        2   XOM  6/10/2011  80.93  81.87  79.72  79.78   92380844   
748        2   XOM  6/17/2011  80.00  80.82  78.33  79.02  100521400   
749        2   XOM  6/24/2011  78.65  81.12  76.78  76.78  118679791   

     percent_change_price  percent_change_volume_over_last_wk  \
0                 3.79267                            0.000000   
1                -4.42849                            1.380223   
2                -2.47066                          -43.024959   
3                 1.63831                            9.355500   
4                 5.93325                            1.987452   
..                    ...                                 ...   
745               3.00424                          -21.355713   
746              -2.52161                           15.221032   
747              -1.42098                           17.508519   
748              -1.22500                            8.811952   
749              -2.37762                           18.064204   

     previous_weeks_volume  next_weeks_open  next_weeks_close  \
0                      0.0            16.71             15.97   
1              239655616.0            16.19             15.79   
2              242963398.0            15.87             16.13   
3              138428495.0            16.18             17.14   
4              151379173.0            17.33             17.37   
..                     ...              ...               ...   
745             86758820.0            83.28             81.18   
746             68230855.0            80.93             79.78   
747             78616295.0            80.00             79.02   
748             92380844.0            78.65             76.78   
749            100521400.0            76.88             82.01   

     percent_change_next_weeks_price  days_to_next_dividend  \
0                          -4.428490                     26   
1                          -2.470660                     19   
2                           1.638310                     12   
3                           5.933250                      5   
4                           0.230814                     97   
..                               ...                    ...   
745                        -2.521610                     75   
746                        -1.420980                     68   
747                        -1.225000                     61   
748                        -2.377620                     54   
749                         6.672740                     47   

     percent_return_next_dividend  
0                        0.182704  
1                        0.187852  
2                        0.189994  
3                        0.185989  
4                        0.175029  
..                            ...  
745                      0.568801  
746                      0.578960  
747                      0.589120  
748                      0.594786  
749                      0.612139  

[750 rows x 16 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   quarter                             750 non-null    int64  
 1   stock                               750 non-null    object 
 2   date                                750 non-null    object 
 3   open                                750 non-null    float64
 4   high                                750 non-null    float64
 5   low                                 750 non-null    float64
 6   close                               750 non-null    float64
 7   volume                              750 non-null    int64  
 8   percent_change_price                750 non-null    float64
 9   percent_change_volume_over_last_wk  750 non-null    float64
 10  previous_weeks_volume               750 non-null    float64
 11  next_weeks_open                     750 non-n

In [9]:
data.corr()

quarter      open      high       low  \
quarter                             1.000000  0.025883  0.024727  0.024730   
open                                0.025883  1.000000  0.999607  0.999344   
high                                0.024727  0.999607  1.000000  0.999419   
low                                 0.024730  0.999344  0.999419  1.000000   
close                               0.022102  0.999044  0.999558  0.999549   
volume                             -0.047599 -0.513424 -0.512240 -0.514850   
percent_change_price               -0.080959  0.061485  0.078656  0.083170   
percent_change_volume_over_last_wk  0.028977 -0.007966 -0.006020 -0.016874   
previous_weeks_volume              -0.024383 -0.495972 -0.495702 -0.495703   
next_weeks_open                     0.021018  0.998942  0.999480  0.999430   
next_weeks_close                    0.019103  0.997787  0.998500  0.998326   
percent_change_next_weeks_price    -0.017460  0.066603  0.069474  0.067320   
days_to_next_dividend              -0.025641 -0.065228 -0.065516 -0.066270   
percent_return_next_dividend       -0.008505 -0.146001 -0.148343 -0.143838   

                                       close    volume  percent_change_price  \
quarter                             0.022102 -0.047599             -0.080959   
open                                0.999044 -0.513424              0.061485   
high                                0.999558 -0.512240              0.078656   
low                                 0.999549 -0.514850              0.083170   
close                               1.000000 -0.514545              0.097980   
volume                             -0.514545  1.000000             -0.138924   
percent_change_price                0.097980 -0.138924              1.000000   
percent_change_volume_over_last_wk -0.015809  0.169133             -0.229568   
previous_weeks_volume              -0.495598  0.817078             -0.071942   
next_weeks_open                     0.999916 -0.514324              0.098270   
next_weeks_close                    0.998854 -0.513456              0.099243   
percent_change_next_weeks_price     0.067664 -0.056389              0.019955   
days_to_next_dividend              -0.065975 -0.055486              0.006217   
percent_return_next_dividend       -0.146417 -0.269735              0.029925   

                                    percent_change_volume_over_last_wk  \
quarter                                                       0.028977   
open                                                         -0.007966   
high                                                         -0.006020   
low                                                          -0.016874   
close                                                        -0.015809   
volume                                                        0.169133   
percent_change_price                                         -0.229568   
percent_change_volume_over_last_wk                            1.000000   
previous_weeks_volume                                        -0.124054   
next_weeks_open                                              -0.014726   
next_weeks_close                                             -0.015061   
percent_change_next_weeks_price                               0.010554   
days_to_next_dividend                                        -0.033117   
percent_return_next_dividend                                 -0.017218   

                                    previous_weeks_volume  next_weeks_open  \
quarter                                         -0.024383         0.021018   
open                                            -0.495972         0.998942   
high                                            -0.495702         0.999480   
low                                             -0.495703         0.999430   
close                                           -0.495598         0.999916   
volume                                           0.817078        -0.514324   
percent_

In [27]:
cols=['open','high','low','close','next_weeks_open','next_weeks_close']

In [28]:
X = data[cols]
Y = data['stock']

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=9)

In [32]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none')

In [33]:
model.fit(X_train,y_train)

F:\Software\Anaconda\envs\exp2\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial', penalty='none')

In [34]:
pred=model.predict(X_test)

In [36]:
from sklearn.metrics import classification_report , accuracy_score
acc=accuracy_score(y_test,pred)
print(acc)

0.1


In [37]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

          AA       0.00      0.00      0.00         5
         AXP       0.17      0.33      0.22         3
          BA       0.00      0.00      0.00         5
         BAC       0.33      0.20      0.25        10
         CAT       0.33      0.17      0.22         6
        CSCO       0.00      0.00      0.00         8
         CVX       0.00      0.00      0.00         4
          DD       0.50      0.12      0.20         8
         DIS       0.00      0.00      0.00         5
          GE       0.18      0.67      0.29         3
          HD       0.00      0.00      0.00         7
         HPQ       0.00      0.00      0.00         2
         IBM       0.50      1.00      0.67         4
        INTC       0.00      0.00      0.00         6
         JNJ       0.00      0.00      0.00         8
         JPM       0.00      0.00      0.00         4
          KO       0.00      0.00      0.00         5
        KRFT       0.00    

F:\Software\Anaconda\envs\exp2\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
F:\Software\Anaconda\envs\exp2\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
F:\Software\Anaconda\envs\exp2\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [1 0 0 2 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 3 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0 0 0 0 1 0 3 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 2 0 0 0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 3 1]
 [0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0